package com.doxbi.friend.world;

import com.doxbi.friend.FriendMod;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.phys.AABB;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.RedstoneLampBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.AttachFace;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;

public final class FriendDimensions {
    public static final ResourceKey<Level> DREAM = ResourceKey.create(Registries.DIMENSION,
            new ResourceLocation(FriendMod.MOD_ID, "dream"));
    public static final ResourceKey<Level> VOID = ResourceKey.create(Registries.DIMENSION,
            new ResourceLocation(FriendMod.MOD_ID, "void"));
    public static final ResourceKey<Level> SKY = ResourceKey.create(Registries.DIMENSION,
            new ResourceLocation(FriendMod.MOD_ID, "sky"));
    public static final ResourceKey<Level> FIFTH = ResourceKey.create(Registries.DIMENSION,
            new ResourceLocation(FriendMod.MOD_ID, "fifth_dimension"));
    public static final ResourceKey<Level> PARADISE = ResourceKey.create(Registries.DIMENSION,
            new ResourceLocation(FriendMod.MOD_ID, "paradise"));

    public static final BlockPos DREAM_START = new BlockPos(0, 11, 0);
    public static final int DREAM_LENGTH = 420;
    public static final BlockPos VOID_START = new BlockPos(0, 80, 0);
    public static final int VOID_LENGTH = 640;
    public static final BlockPos SKY_START = new BlockPos(0, 128, 0);
    public static final int SKY_RADIUS = 96;
    public static final int DREAM_REALM_SIZE = 42;
    public static final BlockPos FIFTH_START = new BlockPos(0, 65, 0);
    public static final BlockPos PARADISE_START = new BlockPos(0, 11, 0);

    private static final BlockPos DREAM_MARKER = new BlockPos(-7, 77, -12);
    private static final BlockPos VOID_MARKER = new BlockPos(-7, 77, -18);
    private static final BlockPos SKY_MARKER = new BlockPos(-7, 124, -18);
    private static final BlockPos DREAM_VERSION_MARKER = new BlockPos(-8, 77, -12);
    private static final BlockPos VOID_VERSION_MARKER = new BlockPos(-8, 77, -18);
    private static final BlockPos SKY_VERSION_MARKER = new BlockPos(-8, 124, -18);
    private static final BlockPos FIFTH_MARKER = new BlockPos(-8, 2, -18);
    private static final BlockPos OLD_FIFTH_MARKER = new BlockPos(-8, 64, -18);
    private static final BlockPos PARADISE_MARKER = new BlockPos(-8, 88, -18);
    private static final BlockPos LEGACY_MARKER = new BlockPos(0, 62, 0);
    private static final BlockPos LEGACY_VERSION_MARKER = new BlockPos(1, 62, 0);

    private FriendDimensions() {
    }

    public static ServerLevel dreamLevel(MinecraftServer server) {
        return server.getLevel(DREAM);
    }

    public static ServerLevel voidLevel(MinecraftServer server) {
        return server.getLevel(VOID);
    }

    public static ServerLevel skyLevel(MinecraftServer server) {
        return server.getLevel(SKY);
    }

    public static ServerLevel fifthLevel(MinecraftServer server) {
        return server.getLevel(FIFTH);
    }

    public static ServerLevel paradiseLevel(MinecraftServer server) {
        return server.getLevel(PARADISE);
    }

    public static boolean sendToDream(ServerPlayer player) {
        return sendToDream(player, 0);
    }

    public static boolean sendToDream(ServerPlayer player, int variant) {
        ServerLevel dream = dreamLevel(player.server);
        if (dream == null) {
            return false;
        }

        BlockPos returnPos = player.blockPosition();
        float returnYaw = player.getYRot();
        float returnPitch = player.getXRot();

        player.stopSleepInBed(true, true);

        // Dream terrain is generated by data/friend/dimension/dream.json.
        // Code only guarantees the single exit door in front of the player.
        int realm = 0;
        BlockPos start = dreamStart(realm);
        dream.setDayTime(6000L);
        dream.setWeatherParameters(20 * 60 * 20, 0, false, false);
        sanitizeDreamSpawn(dream);
        buildDreamExit(dream, dreamExit(realm));
        purgeDreamMobs(dream, DREAM_START);

        CompoundTag data = player.getPersistentData();
        data.putBoolean("friend_dream_session", true);
        data.putInt("friend_dream_variant", realm);
        data.putInt("friend_dream_return_x", returnPos.getX());
        data.putInt("friend_dream_return_y", returnPos.getY());
        data.putInt("friend_dream_return_z", returnPos.getZ());
        data.putFloat("friend_dream_return_yaw", returnYaw);
        data.putFloat("friend_dream_return_pitch", returnPitch);
        data.putLong("friend_dream_exit_at", dream.getGameTime() + 20L * (120 + player.getRandom().nextInt(61)));
        data.putInt("friend_dream_last_chunk_x", Integer.MIN_VALUE);
        data.putInt("friend_dream_last_chunk_z", Integer.MIN_VALUE);

        player.teleportTo(dream, start.getX() + 0.5D, DREAM_START.getY() + 1.0D, start.getZ() + 0.5D, 0.0F, 0.0F);
        player.addEffect(new MobEffectInstance(MobEffects.NIGHT_VISION, 20 * 180, 0, false, false));
        return true;
    }

    public static boolean sendToVoid(ServerPlayer player) {
        ServerLevel voidLevel = voidLevel(player.server);
        if (voidLevel == null) {
            return false;
        }
        ensureVoidCorridor(voidLevel);
        player.stopSleepInBed(true, true);
        player.teleportTo(voidLevel, VOID_START.getX() + 0.5D, VOID_START.getY() + 1.0D, VOID_START.getZ() + 1.5D, 180.0F, 0.0F);
        player.addEffect(new MobEffectInstance(MobEffects.DARKNESS, 20 * 60 * 60, 0, false, false));
        player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 80, 2, false, false));
        return true;
    }

    public static boolean sendToSky(ServerPlayer player) {
        ServerLevel sky = skyLevel(player.server);
        if (sky == null) {
            return false;
        }
        ensureSky(sky);
        player.stopSleepInBed(true, true);
        player.teleportTo(sky, SKY_START.getX() + 0.5D, SKY_START.getY() + 1.0D, SKY_START.getZ() + 0.5D, 180.0F, 0.0F);
        player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 80, 1, false, false));
        player.addEffect(new MobEffectInstance(MobEffects.NIGHT_VISION, 20 * 45, 0, false, false));
        return true;
    }

    public static boolean sendToFifth(ServerPlayer player) {
        ServerLevel fifth = fifthLevel(player.server);
        if (fifth == null) {
            return false;
        }
        ensureFifth(fifth);
        player.stopSleepInBed(true, true);
        player.teleportTo(fifth, FIFTH_START.getX() + 0.5D, FIFTH_START.getY() + 1.0D, FIFTH_START.getZ() + 0.5D, 0.0F, 35.0F);
        player.addEffect(new MobEffectInstance(MobEffects.DARKNESS, 45, 0, false, false));
        player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 20 * 15, 6, false, false));
        return true;
    }

    public static boolean sendToParadise(ServerPlayer player) {
        // Paradise was removed from the release build. Keep the method as a safe stub
        // so old commands/saves fail gracefully instead of crashing missing dimensions.
        return false;
    }

    public static BlockPos dreamStart(int variant) {
        // Variants are disabled for the new Dream design. Every Dream starts in the same clean field.
        return DREAM_START;
    }

    public static BlockPos dreamExit(int variant) {
        // One visible door directly in front of the player after teleporting into Dream.
        return DREAM_START.offset(0, 0, 12);
    }

    public static boolean sendHomeFromDream(ServerPlayer player) {
        return sendHomeFromDream(player, null);
    }

    public static boolean sendHomeFromDream(ServerPlayer player, BlockPos preferredTarget) {
        ServerLevel overworld = player.server.getLevel(Level.OVERWORLD);
        if (overworld == null) {
            return false;
        }
        overworld.setDayTime(1000L);
        BlockPos target = preferredTarget;
        if (target == null) {
            target = player.getRespawnPosition();
        }
        if (target == null) {
            target = overworld.getSharedSpawnPos();
        }
        CompoundTag data = player.getPersistentData();
        float yaw = data.contains("friend_dream_return_yaw") ? data.getFloat("friend_dream_return_yaw") : player.getYRot();
        float pitch = data.contains("friend_dream_return_pitch") ? data.getFloat("friend_dream_return_pitch") : 0.0F;
        clearDreamSession(player);
        player.teleportTo(overworld, target.getX() + 0.5D, target.getY() + 1.0D, target.getZ() + 0.5D, yaw, pitch);
        player.addEffect(new MobEffectInstance(MobEffects.WEAKNESS, 20 * 12, 0, false, false));
        return true;
    }

    public static void ensureDreamCorridor(ServerLevel level) {
        ensureDreamCorridor(level, -1);
    }

    public static void ensureDreamCorridor(ServerLevel level, int variant) {
        // Compatibility method. Old code built a narrow corridor here.
        // New dream logic builds an open wheat field instead.
        int realm = Math.max(0, variant);
        buildDreamExit(level, dreamExit(realm));
    }

    public static void ensureDreamRealm(ServerLevel level, int variant) {
        // Compatibility method for old variant-based dream calls.
        // Variants now choose spawn offsets, not boxed rooms.
        ensureDreamCorridor(level, variant);
    }

    public static void ensureDreamFieldAround(ServerLevel level, BlockPos center, int radius) {
        // Terrain is generated by the dimension flat generator.
        // Do not mass-place blocks here: doing so caused bed-click freezes and ugly built-looking worlds.
    }

    public static void tickDreamField(ServerPlayer player) {
        if (!player.level().dimension().equals(DREAM) || !(player.level() instanceof ServerLevel level)) {
            return;
        }
        level.setDayTime(6000L);
        level.setWeatherParameters(20 * 60 * 20, 0, false, false);
        sanitizeDreamSpawn(level);
        buildDreamExit(level, dreamExit(0));
        purgeDreamMobs(level, player.blockPosition());
    }

    public static boolean shouldAutoLeaveDream(ServerPlayer player) {
        if (!(player.level() instanceof ServerLevel level) || !level.dimension().equals(DREAM)) {
            return false;
        }
        CompoundTag data = player.getPersistentData();
        long exitAt = data.getLong("friend_dream_exit_at");
        if (exitAt > 0L && level.getGameTime() >= exitAt) {
            return true;
        }
        return isNearDreamExit(player.blockPosition(), data.getInt("friend_dream_variant"));
    }

    public static boolean isDreamExitDoor(BlockPos pos, int variant) {
        BlockPos exit = dreamExit(variant);
        return pos.equals(exit) || pos.equals(exit.above());
    }

    public static boolean isNearDreamExit(BlockPos pos, int variant) {
        return pos.closerThan(dreamExit(variant), 2.15D);
    }

    public static BlockPos dreamReturnPos(ServerPlayer player) {
        CompoundTag data = player.getPersistentData();
        if (data.contains("friend_dream_return_x") && data.contains("friend_dream_return_y") && data.contains("friend_dream_return_z")) {
            return new BlockPos(data.getInt("friend_dream_return_x"), data.getInt("friend_dream_return_y"), data.getInt("friend_dream_return_z"));
        }
        return null;
    }

    private static void clearDreamSession(ServerPlayer player) {
        CompoundTag data = player.getPersistentData();
        data.remove("friend_dream_session");
        data.remove("friend_dream_variant");
        data.remove("friend_dream_return_x");
        data.remove("friend_dream_return_y");
        data.remove("friend_dream_return_z");
        data.remove("friend_dream_return_yaw");
        data.remove("friend_dream_return_pitch");
        data.remove("friend_dream_exit_at");
        data.remove("friend_dream_last_chunk_x");
        data.remove("friend_dream_last_chunk_z");
    }

    private static void clearLegacyDreamCorridor(ServerLevel level) {
        if (!level.getBlockState(DREAM_MARKER).is(Blocks.BEDROCK) && !level.getBlockState(DREAM_VERSION_MARKER).is(Blocks.BEDROCK)) {
            return;
        }
        for (int x = -6; x <= 6; x++) {
            for (int z = -12; z <= DREAM_LENGTH + 6; z++) {
                for (int y = 78; y <= 87; y++) {
                    level.setBlock(new BlockPos(x, y, z), Blocks.AIR.defaultBlockState(), 2);
                }
            }
        }
        level.setBlock(DREAM_MARKER, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(DREAM_VERSION_MARKER, Blocks.AIR.defaultBlockState(), 3);
    }

    private static int dreamHash(int x, int z) {
        int h = x * 73428767 ^ z * 912931 ^ 0x5f3759df;
        h ^= h >>> 13;
        h *= 1274126177;
        h ^= h >>> 16;
        return h & 0x7fffffff;
    }

    private static void buildLonelyDoor(ServerLevel level, BlockPos base) {
        level.setBlock(base.below(), Blocks.COARSE_DIRT.defaultBlockState(), 2);
        level.setBlock(base, Blocks.DARK_OAK_DOOR.defaultBlockState(), 3);
        level.setBlock(base.above(), Blocks.DARK_OAK_DOOR.defaultBlockState().setValue(net.minecraft.world.level.block.DoorBlock.HALF, net.minecraft.world.level.block.state.properties.DoubleBlockHalf.UPPER), 3);
        level.setBlock(base.offset(1, 0, 0), Blocks.BLACK_WOOL.defaultBlockState(), 2);
        level.setBlock(base.offset(-1, 0, 0), Blocks.BLACK_WOOL.defaultBlockState(), 2);
    }

    private static void buildRedLightPost(ServerLevel level, BlockPos base) {
        for (int y = 0; y <= 3; y++) {
            level.setBlock(base.above(y), Blocks.IRON_BARS.defaultBlockState(), 2);
        }
        level.setBlock(base.above(4), Blocks.REDSTONE_LAMP.defaultBlockState().setValue(RedstoneLampBlock.LIT, true), 3);
        level.setBlock(base.above(5), Blocks.REDSTONE_BLOCK.defaultBlockState(), 2);
    }

    private static void buildScarecrow(ServerLevel level, BlockPos base) {
        level.setBlock(base, Blocks.OAK_FENCE.defaultBlockState(), 2);
        level.setBlock(base.above(), Blocks.OAK_FENCE.defaultBlockState(), 2);
        level.setBlock(base.above(2), Blocks.HAY_BLOCK.defaultBlockState(), 2);
        level.setBlock(base.above(3), Blocks.CARVED_PUMPKIN.defaultBlockState(), 2);
        level.setBlock(base.offset(1, 2, 0), Blocks.OAK_FENCE.defaultBlockState(), 2);
        level.setBlock(base.offset(-1, 2, 0), Blocks.OAK_FENCE.defaultBlockState(), 2);
    }

    private static BlockState dreamFloor(int realm) {
        return switch (realm) {
            case 1 -> Blocks.BLACK_CONCRETE.defaultBlockState();
            case 2 -> Blocks.STRIPPED_DARK_OAK_WOOD.defaultBlockState();
            case 3 -> Blocks.BLUE_ICE.defaultBlockState();
            case 4 -> Blocks.RED_NETHER_BRICKS.defaultBlockState();
            case 5 -> Blocks.SMOOTH_STONE.defaultBlockState();
            case 6 -> Blocks.GRAY_STAINED_GLASS.defaultBlockState();
            case 7 -> Blocks.WHITE_CONCRETE.defaultBlockState();
            case 8 -> Blocks.LIGHT_BLUE_STAINED_GLASS.defaultBlockState();
            case 9 -> Blocks.DEEPSLATE_TILES.defaultBlockState();
            default -> Blocks.MOSSY_COBBLESTONE.defaultBlockState();
        };
    }

    private static BlockState dreamWall(int realm) {
        return switch (realm) {
            case 1 -> Blocks.OBSIDIAN.defaultBlockState();
            case 2 -> Blocks.DARK_OAK_PLANKS.defaultBlockState();
            case 3 -> Blocks.LIGHT_BLUE_CONCRETE.defaultBlockState();
            case 4 -> Blocks.NETHER_BRICKS.defaultBlockState();
            case 5 -> Blocks.POLISHED_ANDESITE.defaultBlockState();
            case 6 -> Blocks.BLACK_STAINED_GLASS.defaultBlockState();
            case 7 -> Blocks.QUARTZ_BLOCK.defaultBlockState();
            case 8 -> Blocks.BARRIER.defaultBlockState();
            case 9 -> Blocks.POLISHED_DEEPSLATE.defaultBlockState();
            default -> Blocks.MOSSY_STONE_BRICKS.defaultBlockState();
        };
    }

    private static BlockState dreamAccent(int realm) {
        return switch (realm) {
            case 1 -> Blocks.CRYING_OBSIDIAN.defaultBlockState();
            case 2 -> Blocks.SOUL_LANTERN.defaultBlockState();
            case 3 -> Blocks.SEA_LANTERN.defaultBlockState();
            case 4 -> Blocks.REDSTONE_LAMP.defaultBlockState().setValue(RedstoneLampBlock.LIT, true);
            case 5 -> Blocks.IRON_BARS.defaultBlockState();
            case 6 -> Blocks.TINTED_GLASS.defaultBlockState();
            case 7 -> Blocks.RED_CONCRETE.defaultBlockState();
            case 8 -> Blocks.WHITE_STAINED_GLASS.defaultBlockState();
            case 9 -> Blocks.GOLD_BLOCK.defaultBlockState();
            default -> Blocks.SCULK.defaultBlockState();
        };
    }

    private static void decorateDreamRealm(ServerLevel level, int realm, BlockPos start, BlockState accent) {
        int y = start.getY() + 1;
        switch (realm) {
            case 1 -> {
                for (int z = 4; z <= 34; z += 6) {
                    level.setBlock(start.offset(-12, y + 3, z), Blocks.BLACK_STAINED_GLASS.defaultBlockState(), 2);
                    level.setBlock(start.offset(12, y + 3, z + 2), Blocks.BLACK_STAINED_GLASS.defaultBlockState(), 2);
                    level.setBlock(start.offset(-12, y + 2, z), accent, 2);
                    level.setBlock(start.offset(12, y + 2, z + 2), accent, 2);
                }
            }
            case 2 -> {
                for (int x = -15; x <= 15; x += 10) {
                    level.setBlock(start.offset(x, y, 8), Blocks.DARK_OAK_STAIRS.defaultBlockState(), 2);
                    level.setBlock(start.offset(x, y, 18), Blocks.CHEST.defaultBlockState(), 2);
                    level.setBlock(start.offset(x, y, 28), Blocks.RED_BED.defaultBlockState(), 2);
                }
            }
            case 3 -> {
                for (int x = -18; x <= 18; x += 6) {
                    level.setBlock(start.offset(x, y, 10), Blocks.IRON_DOOR.defaultBlockState(), 2);
                    level.setBlock(start.offset(x, y + 1, 10), Blocks.IRON_BARS.defaultBlockState(), 2);
                    level.setBlock(start.offset(x, y, 26), Blocks.BLUE_CARPET.defaultBlockState(), 2);
                }
            }
            case 4 -> {
                for (int z = 5; z <= 36; z += 5) {
                    for (int x = -16; x <= 16; x += 8) {
                        level.setBlock(start.offset(x, y, z), Blocks.CRIMSON_FENCE.defaultBlockState(), 2);
                        level.setBlock(start.offset(x, y + 1, z), Blocks.CRIMSON_FENCE.defaultBlockState(), 2);
                    }
                }
            }
            case 5 -> {
                for (int i = 0; i < 10; i++) {
                    int z = 5 + i * 3;
                    int x = -10 + i * 2;
                    level.setBlock(start.offset(x, y + i % 4, z), Blocks.SMOOTH_STONE_SLAB.defaultBlockState(), 2);
                    level.setBlock(start.offset(x + 1, y + i % 4, z), Blocks.SMOOTH_STONE_SLAB.defaultBlockState(), 2);
                }
            }
            case 6 -> {
                for (int z = 4; z <= 36; z += 4) {
                    level.setBlock(start.offset(-8, y + 2, z), Blocks.TINTED_GLASS.defaultBlockState(), 2);
                }
            }
            case 7 -> {
                for (int x = -18; x <= 18; x += 6) {
                    for (int z = 4; z <= 34; z += 8) {
                        level.setBlock(start.offset(x, y, z), Blocks.QUARTZ_PILLAR.defaultBlockState(), 2);
                        level.setBlock(start.offset(x, y + 1, z), Blocks.QUARTZ_PILLAR.defaultBlockState(), 2);
                        level.setBlock(start.offset(x, y + 2, z), Blocks.QUARTZ_PILLAR.defaultBlockState(), 2);
                    }
                }
            }
            case 8 -> {
                for (int x = -18; x <= 18; x += 9) {
                    for (int z = 3; z <= 35; z += 8) {
                        level.setBlock(start.offset(x, y, z), Blocks.WHITE_WOOL.defaultBlockState(), 2);
                        level.setBlock(start.offset(x + 1, y, z), Blocks.WHITE_CARPET.defaultBlockState(), 2);
                    }
                }
            }
            case 9 -> {
                for (int z = 5; z <= 35; z += 5) {
                    level.setBlock(start.offset(-14, y + 2, z), Blocks.BELL.defaultBlockState(), 2);
                    level.setBlock(start.offset(14, y + 2, z), Blocks.BELL.defaultBlockState(), 2);
                    level.setBlock(start.offset(0, y, z), Blocks.GOLD_BLOCK.defaultBlockState(), 2);
                }
            }
            default -> {
                for (int z = 5; z <= 35; z += 6) {
                    level.setBlock(start.offset(-10, y, z), Blocks.OAK_DOOR.defaultBlockState(), 2);
                    level.setBlock(start.offset(10, y, z + 2), Blocks.OAK_DOOR.defaultBlockState(), 2);
                    level.setBlock(start.offset(0, y, z), Blocks.SCULK_VEIN.defaultBlockState(), 2);
                }
            }
        }
    }


    private static void sanitizeDreamSpawn(ServerLevel level) {
        // The Dream terrain comes from the flat generator. This method only removes old junk
        // from previously generated test worlds around the spawn/exit so the player never
        // spawns in barriers, flowing water, or leftover block portals.
        clearDreamJunk(level, DREAM_START, 5);
        clearDreamJunk(level, dreamExit(0), 4);
    }

    private static void clearDreamJunk(ServerLevel level, BlockPos center, int radius) {
        int floorY = DREAM_START.getY() - 1;
        for (int x = -radius; x <= radius; x++) {
            for (int z = -radius; z <= radius; z++) {
                for (int y = floorY + 1; y <= floorY + 4; y++) {
                    BlockPos pos = new BlockPos(center.getX() + x, y, center.getZ() + z);
                    BlockState state = level.getBlockState(pos);
                    if (state.is(Blocks.BARRIER) || state.is(Blocks.WATER) || state.is(Blocks.LAVA)
                            || state.is(Blocks.NETHER_PORTAL) || state.is(Blocks.END_PORTAL)
                            || state.is(Blocks.END_PORTAL_FRAME)) {
                        level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
                    }
                }
            }
        }
    }

    private static void purgeDreamMobs(ServerLevel level, BlockPos center) {
        AABB area = new AABB(center).inflate(96.0D, 48.0D, 96.0D);
        for (Mob mob : level.getEntitiesOfClass(Mob.class, area, mob -> !(mob instanceof net.minecraft.world.entity.animal.Animal))) {
            mob.discard();
        }
    }

    private static BlockPos dreamExitMarker(BlockPos exit) {
        // Hidden one-shot marker. If the player breaks the exit door, this marker prevents
        // Dream tick/setup code from rebuilding it every tick and duplicating door items.
        return new BlockPos(exit.getX(), DREAM_START.getY() - 3, exit.getZ());
    }

    private static boolean isValidDreamExitDoor(ServerLevel level, BlockPos lowerPos) {
        BlockState lower = level.getBlockState(lowerPos);
        BlockState upper = level.getBlockState(lowerPos.above());
        return lower.is(Blocks.DARK_OAK_DOOR)
                && upper.is(Blocks.DARK_OAK_DOOR)
                && lower.hasProperty(DoorBlock.HALF)
                && upper.hasProperty(DoorBlock.HALF)
                && lower.getValue(DoorBlock.HALF) == DoubleBlockHalf.LOWER
                && upper.getValue(DoorBlock.HALF) == DoubleBlockHalf.UPPER;
    }

    private static void buildDreamExit(ServerLevel level, BlockPos exit) {
        int y = DREAM_START.getY();
        BlockPos lowerPos = new BlockPos(exit.getX(), y, exit.getZ());
        BlockPos upperPos = lowerPos.above();
        BlockPos marker = dreamExitMarker(exit);

        // IMPORTANT:
        // Build the Dream exit only once. Rebuilding a vanilla DoorBlock while it is being
        // broken causes the lower/upper half to update repeatedly, which can duplicate doors.
        if (level.getBlockState(marker).is(Blocks.BEDROCK)) {
            return;
        }

        if (isValidDreamExitDoor(level, lowerPos)) {
            level.setBlock(marker, Blocks.BEDROCK.defaultBlockState(), 2);
            return;
        }

        // Clean a tiny area once. Use flag 2 where possible so this setup pass does not behave
        // like repeated player block-breaking.
        level.setBlock(lowerPos, Blocks.AIR.defaultBlockState(), 2);
        level.setBlock(upperPos, Blocks.AIR.defaultBlockState(), 2);
        level.setBlock(lowerPos.below(), Blocks.FARMLAND.defaultBlockState(), 2);

        // One readable exit door only. No portal frame, no random doors, no decorative block structures.
        for (int dx = -1; dx <= 1; dx++) {
            for (int dz = -1; dz <= 1; dz++) {
                for (int dy = 0; dy <= 2; dy++) {
                    BlockPos clear = new BlockPos(exit.getX() + dx, y + dy, exit.getZ() + dz);
                    if (!clear.equals(lowerPos) && !clear.equals(upperPos)) {
                        BlockState existing = level.getBlockState(clear);
                        if (existing.is(Blocks.BARRIER) || existing.is(Blocks.WATER) || existing.is(Blocks.LAVA)
                                || existing.is(Blocks.NETHER_PORTAL) || existing.is(Blocks.END_PORTAL)
                                || existing.is(Blocks.END_PORTAL_FRAME)) {
                            level.setBlock(clear, Blocks.AIR.defaultBlockState(), 2);
                        }
                    }
                }
            }
        }

        BlockState lower = Blocks.DARK_OAK_DOOR.defaultBlockState()
                .setValue(DoorBlock.FACING, Direction.SOUTH)
                .setValue(DoorBlock.HALF, DoubleBlockHalf.LOWER);
        BlockState upper = Blocks.DARK_OAK_DOOR.defaultBlockState()
                .setValue(DoorBlock.FACING, Direction.SOUTH)
                .setValue(DoorBlock.HALF, DoubleBlockHalf.UPPER);

        level.setBlock(lowerPos, lower, 2);
        level.setBlock(upperPos, upper, 2);
        level.setBlock(marker, Blocks.BEDROCK.defaultBlockState(), 2);
    }

    public static void ensureVoidCorridor(ServerLevel level) {
        clearLegacyBarrierMarkers(level);
        if (level.getBlockState(VOID_MARKER).is(Blocks.BEDROCK) && level.getBlockState(VOID_VERSION_MARKER).is(Blocks.BEDROCK)) {
            return;
        }
        level.setBlock(VOID_MARKER, Blocks.BEDROCK.defaultBlockState(), 3);
        level.setBlock(VOID_VERSION_MARKER, Blocks.BEDROCK.defaultBlockState(), 3);
        for (int z = -16; z <= VOID_LENGTH + 4; z++) {
            for (int x = -5; x <= 5; x++) {
                for (int y = 78; y <= 88; y++) {
                    BlockPos pos = new BlockPos(x, y, z);
                    boolean shell = x == -5 || x == 5 || y == 78 || y == 88 || z == -16 || z == VOID_LENGTH + 4;
                    level.setBlock(pos, shell ? Blocks.BEDROCK.defaultBlockState() : Blocks.AIR.defaultBlockState(), 2);
                }
            }
        }
        for (int z = 20; z <= VOID_LENGTH; z += 80) {
            level.setBlock(new BlockPos(-4, 82, z), Blocks.SCULK.defaultBlockState(), 2);
            level.setBlock(new BlockPos(4, 82, z + 12), Blocks.SCULK.defaultBlockState(), 2);
        }
    }

    public static void ensureSky(ServerLevel level) {
        clearLegacyBarrierMarkers(level);
        if (level.getBlockState(SKY_MARKER).is(Blocks.BEDROCK) && level.getBlockState(SKY_VERSION_MARKER).is(Blocks.BEDROCK)) {
            return;
        }
        level.setBlock(SKY_MARKER, Blocks.BEDROCK.defaultBlockState(), 3);
        level.setBlock(SKY_VERSION_MARKER, Blocks.BEDROCK.defaultBlockState(), 3);
        int y = SKY_START.getY();
        for (int x = -SKY_RADIUS; x <= SKY_RADIUS; x++) {
            for (int z = -SKY_RADIUS; z <= SKY_RADIUS; z++) {
                boolean edge = Math.abs(x) == SKY_RADIUS || Math.abs(z) == SKY_RADIUS;
                level.setBlock(new BlockPos(x, y, z), Blocks.BARRIER.defaultBlockState(), 2);
                if (edge) {
                    for (int h = 1; h <= 7; h++) {
                        level.setBlock(new BlockPos(x, y + h, z), Blocks.BARRIER.defaultBlockState(), 2);
                    }
                }
                if ((x * x + z * z) % 173 == 0) {
                    level.setBlock(new BlockPos(x, y + 1, z), Blocks.WHITE_STAINED_GLASS.defaultBlockState(), 2);
                }
            }
        }
        buildSkyChoice(level, new BlockPos(-36, y + 1, 56), true);
        buildSkyChoice(level, new BlockPos(36, y + 1, 56), false);
        for (int z = 5; z <= 52; z += 7) {
            level.setBlock(new BlockPos(-36, y + 1, z), Blocks.SEA_LANTERN.defaultBlockState(), 2);
            level.setBlock(new BlockPos(36, y + 1, z), Blocks.CRYING_OBSIDIAN.defaultBlockState(), 2);
        }
    }

    public static void ensureFifth(ServerLevel level) {
        clearLegacyBarrierMarkers(level);
        if (level.getBlockState(OLD_FIFTH_MARKER).is(Blocks.BEDROCK)) {
            level.setBlock(OLD_FIFTH_MARKER, Blocks.AIR.defaultBlockState(), 3);
        }
        if (!level.getBlockState(FIFTH_MARKER).is(Blocks.BEDROCK)) {
            level.setBlock(FIFTH_MARKER, Blocks.BEDROCK.defaultBlockState(), 3);
        }
        // IMPORTANT:
        // Do not build any handmade platform in the bad-ending / fifth dimension.
        // Terrain must come from the dimension generator, like Nether/End style worlds.
    }

    public static void ensureFifthField(ServerLevel level, BlockPos center, int radius) {
        // Removed. This used to build a square dirt platform around the player.
        // Bad ending must not create platforms; it should use generated terrain only.
    }

    public static void ensureParadise(ServerLevel level) {
        // Paradise removed from release build.
    }

    public static void tickParadiseField(ServerPlayer player) {
        // Paradise removed from release build.
    }

    public static void ensureParadiseFieldAround(ServerLevel level, BlockPos center, int radius) {
        // Paradise terrain is generated by data/friend/dimension/paradise.json.
        // Keep code from building noisy handmade fields over generated chunks.
    }

    public static void ensureParadiseChoice(ServerLevel level) {
        // Paradise removed from release build.
    }

    public static void clearParadiseChoice(ServerLevel level) {
        // Paradise removed from release build.
    }

    private static void buildParadiseChoice(ServerLevel level) {
        int y = PARADISE_START.getY() + 1;
        // Small clean choice area, not a portal room.
        for (int x = -9; x <= 9; x++) {
            for (int z = 4; z <= 14; z++) {
                level.setBlock(new BlockPos(x, y - 1, z), Blocks.SMOOTH_QUARTZ.defaultBlockState(), 3);
                level.setBlock(new BlockPos(x, y, z), Blocks.AIR.defaultBlockState(), 3);
                level.setBlock(new BlockPos(x, y + 1, z), Blocks.AIR.defaultBlockState(), 3);
            }
        }
        BlockState button = Blocks.STONE_BUTTON.defaultBlockState()
                .setValue(ButtonBlock.FACE, AttachFace.FLOOR)
                .setValue(ButtonBlock.FACING, Direction.NORTH);
        level.setBlock(new BlockPos(-5, y, 10), button, 3);
        level.setBlock(new BlockPos(5, y, 10), button, 3);
        level.setBlock(new BlockPos(-5, y - 1, 10), Blocks.QUARTZ_BLOCK.defaultBlockState(), 3);
        level.setBlock(new BlockPos(5, y - 1, 10), Blocks.QUARTZ_BLOCK.defaultBlockState(), 3);
        level.setBlock(new BlockPos(-5, y, 7), Blocks.LECTERN.defaultBlockState(), 3);
        level.setBlock(new BlockPos(5, y, 7), Blocks.LECTERN.defaultBlockState(), 3);
    }

    private static void buildSkyChoice(ServerLevel level, BlockPos center, boolean good) {
        BlockState frame = good ? Blocks.SEA_LANTERN.defaultBlockState() : Blocks.CRYING_OBSIDIAN.defaultBlockState();
        BlockState pane = good ? Blocks.LIGHT_BLUE_STAINED_GLASS.defaultBlockState() : Blocks.BLACK_STAINED_GLASS.defaultBlockState();
        for (int x = -3; x <= 3; x++) {
            for (int y = 0; y <= 5; y++) {
                boolean edge = Math.abs(x) == 3 || y == 0 || y == 5;
                level.setBlock(center.offset(x, y, 0), edge ? frame : pane, 3);
            }
        }
    }

    private static void clearLegacyBarrierMarkers(ServerLevel level) {
        if (level.getBlockState(LEGACY_MARKER).is(Blocks.BARRIER)) {
            level.setBlock(LEGACY_MARKER, Blocks.AIR.defaultBlockState(), 3);
        }
        if (level.getBlockState(LEGACY_VERSION_MARKER).is(Blocks.BARRIER)) {
            level.setBlock(LEGACY_VERSION_MARKER, Blocks.AIR.defaultBlockState(), 3);
        }
    }
}
