package com.doxbi.friend.stalking;

public enum FriendStalkingState {
    INACTIVE,
    SELECTING_TARGET,
    SCANNING_CONTEXT,
    SEARCHING_COVER,
    STAGING_AT_COVER,
    HIDDEN_BEHIND_COVER,
    PEEKING_LEFT,
    PEEKING_RIGHT,
    PEEKING_TOP,
    PEEKING_BOTTOM,
    PEEKING_WINDOW,
    PEEKING_TREE,
    LOW_CEILING_PEEK,
    OBSERVING_DISTANT,
    SPOTTED,
    RETREATING,
    SLIPPING_BEHIND,
    RELOCATING,
    REVEALING,
    CHASE_TRANSITION,
    CHASING,
    RAGE_CHASING,
    COOLDOWN
}
