package com.doxbi.friend.stalking;

public enum MinePeekAnchorType {
    MINESHAFT_SUPPORT_LEFT,
    MINESHAFT_SUPPORT_RIGHT,
    RAIL_TUNNEL_END,
    COBWEB_SILHOUETTE,
    CROSS_CORRIDOR_EDGE,
    BEAM_SHADOW,
    FENCE_GAP_WATCHER,
    PLANK_CORNER_PEEK,

    PLAYER_BRANCH_ENTRANCE,
    TORCH_GAP_SHADOW,
    DEAD_END_EXIT,
    STAIRCASE_CORNER,
    LADDER_SHAFT_EDGE,
    RETURN_PATH_WATCHER,
    ORE_POCKET_PEEK,
    STRIP_MINE_END,
    SIDE_TUNNEL_FACE_PEEK,
    LAST_TORCH_WATCHER,

    CAVE_LEDGE_WATCHER,
    DARK_POCKET_PEEK,
    WATERFALL_SILHOUETTE,
    LAVA_BACKLIGHT_SILHOUETTE,
    CAVE_WALL_EDGE,
    CEILING_SHADOW,
    VERTICAL_DROP_WATCHER,

    TRANSITION_EDGE,
    PLAYER_TUNNEL_TO_CAVE_EXIT,
    MINESHAFT_TO_CAVE_CROSSING,
    ARTIFICIAL_TO_NATURAL_BOUNDARY
}
