package com.doxbi.friend.stalking;

public enum MineActivityType {
    PLAYER_MOVED_THROUGH,
    PLAYER_MINED_BLOCK,
    PLAYER_PLACED_TORCH,
    PLAYER_ENTERED_BRANCH,
    PLAYER_REACHED_DEAD_END,
    PLAYER_MOVED_FAR,
    PLAYER_ENTERED_CAVE,
    PLAYER_USED_LADDER,
    PLAYER_USED_STAIRS,
    PLAYER_FOUND_ORE_POCKET
}
